import { Injectable } from '@nestjs/common';

/**
 * Maps raw biomarker names (from OCR or manual input) to standardized keys,
 * human-readable names, and Prisma BiomarkerCategory enum values.
 *
 * Prisma enum BiomarkerCategory:
 *   HEMOGRAMA | LIPIDIOS | METABOLICO | TIREOIDE | HEPATICO | RENAL
 *   | VITAMINAS_MINERAIS | HORMONIOS | INFLAMACAO | MARCADORES_TUMORAIS
 *   | URINARIO | OUTROS
 */
@Injectable()
export class BiomarkerNormalizerService {
  private dictionary: Record<string, { key: string; name: string; category: string }> = {
    // ── METABOLICO ──
    'GLUCOSE': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'GLICOSE': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'GLICEMIA': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'GLICOSE DE JEJUM': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'GLICEMIA DE JEJUM': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'GLUCOSE SERICA': { key: 'GLUCOSE', name: 'Glicose de Jejum', category: 'METABOLICO' },
    'HBA1C': { key: 'HBA1C', name: 'Hemoglobina Glicada (HbA1c)', category: 'METABOLICO' },
    'HEMOGLOBINA GLICADA': { key: 'HBA1C', name: 'Hemoglobina Glicada (HbA1c)', category: 'METABOLICO' },
    'HEMOGLOBINA GLICADA HBA1C': { key: 'HBA1C', name: 'Hemoglobina Glicada (HbA1c)', category: 'METABOLICO' },
    'HEMOGLOBINA GLICADA - HBA1C': { key: 'HBA1C', name: 'Hemoglobina Glicada (HbA1c)', category: 'METABOLICO' },
    'ESTIMATED_AVERAGE_GLUCOSE': { key: 'ESTIMATED_AVERAGE_GLUCOSE', name: 'Glicose Média Estimada (GME)', category: 'METABOLICO' },
    'GLICOSE MEDIA ESTIMADA': { key: 'ESTIMATED_AVERAGE_GLUCOSE', name: 'Glicose Média Estimada (GME)', category: 'METABOLICO' },
    'GLICOSE MEDIA ESTIMADA (GME)': { key: 'ESTIMATED_AVERAGE_GLUCOSE', name: 'Glicose Média Estimada (GME)', category: 'METABOLICO' },
    'GME': { key: 'ESTIMATED_AVERAGE_GLUCOSE', name: 'Glicose Média Estimada (GME)', category: 'METABOLICO' },
    'INSULIN': { key: 'INSULIN', name: 'Insulina de Jejum', category: 'METABOLICO' },
    'INSULINA': { key: 'INSULIN', name: 'Insulina de Jejum', category: 'METABOLICO' },
    'INSULINA DE JEJUM': { key: 'INSULIN', name: 'Insulina de Jejum', category: 'METABOLICO' },
    'INSULINEMIA': { key: 'INSULIN', name: 'Insulina de Jejum', category: 'METABOLICO' },
    'HOMA_IR': { key: 'HOMA_IR', name: 'HOMA-IR', category: 'METABOLICO' },
    'HOMA-IR': { key: 'HOMA_IR', name: 'HOMA-IR', category: 'METABOLICO' },
    'INDICE HOMA-IR': { key: 'HOMA_IR', name: 'HOMA-IR', category: 'METABOLICO' },
    'HOMA_BETA': { key: 'HOMA_BETA', name: 'HOMA-Beta', category: 'METABOLICO' },
    'HOMA-BETA': { key: 'HOMA_BETA', name: 'HOMA-Beta', category: 'METABOLICO' },
    'ALBUMIN': { key: 'ALBUMIN', name: 'Albumina', category: 'METABOLICO' },
    'ALBUMINA': { key: 'ALBUMIN', name: 'Albumina', category: 'METABOLICO' },
    'ALBUMINA SERICA': { key: 'ALBUMIN', name: 'Albumina', category: 'METABOLICO' },
    'ALBUMINA SÉRICA': { key: 'ALBUMIN', name: 'Albumina', category: 'METABOLICO' },
    'TOTAL_PROTEIN': { key: 'TOTAL_PROTEIN', name: 'Proteínas Totais', category: 'METABOLICO' },
    'PROTEINAS TOTAIS': { key: 'TOTAL_PROTEIN', name: 'Proteínas Totais', category: 'METABOLICO' },
    'GLOBULIN': { key: 'GLOBULIN', name: 'Globulinas', category: 'METABOLICO' },
    'GLOBULINAS': { key: 'GLOBULIN', name: 'Globulinas', category: 'METABOLICO' },
    'LACTATE': { key: 'LACTATE', name: 'Lactato (Ácido Láctico)', category: 'METABOLICO' },
    'LACTATO': { key: 'LACTATE', name: 'Lactato (Ácido Láctico)', category: 'METABOLICO' },
    'ACIDO LACTICO': { key: 'LACTATE', name: 'Lactato (Ácido Láctico)', category: 'METABOLICO' },

    // ── LIPIDIOS ──
    'TOTAL_CHOLESTEROL': { key: 'TOTAL_CHOLESTEROL', name: 'Colesterol Total', category: 'LIPIDIOS' },
    'COLESTEROL TOTAL': { key: 'TOTAL_CHOLESTEROL', name: 'Colesterol Total', category: 'LIPIDIOS' },
    'COLESTEROL-TOTAL': { key: 'TOTAL_CHOLESTEROL', name: 'Colesterol Total', category: 'LIPIDIOS' },
    'LDL': { key: 'LDL', name: 'Colesterol LDL', category: 'LIPIDIOS' },
    'COLESTEROL LDL': { key: 'LDL', name: 'Colesterol LDL', category: 'LIPIDIOS' },
    'LDL-C': { key: 'LDL', name: 'Colesterol LDL', category: 'LIPIDIOS' },
    'COLESTEROL - LDL': { key: 'LDL', name: 'Colesterol LDL', category: 'LIPIDIOS' },
    'HDL': { key: 'HDL', name: 'Colesterol HDL', category: 'LIPIDIOS' },
    'COLESTEROL HDL': { key: 'HDL', name: 'Colesterol HDL', category: 'LIPIDIOS' },
    'HDL-C': { key: 'HDL', name: 'Colesterol HDL', category: 'LIPIDIOS' },
    'COLESTEROL - HDL': { key: 'HDL', name: 'Colesterol HDL', category: 'LIPIDIOS' },
    'VLDL': { key: 'VLDL', name: 'Colesterol VLDL', category: 'LIPIDIOS' },
    'COLESTEROL VLDL': { key: 'VLDL', name: 'Colesterol VLDL', category: 'LIPIDIOS' },
    'VLDL-C': { key: 'VLDL', name: 'Colesterol VLDL', category: 'LIPIDIOS' },
    'NON_HDL': { key: 'NON_HDL', name: 'Colesterol Não-HDL', category: 'LIPIDIOS' },
    'COLESTEROL NAO HDL': { key: 'NON_HDL', name: 'Colesterol Não-HDL', category: 'LIPIDIOS' },
    'COLESTEROL NAO-HDL': { key: 'NON_HDL', name: 'Colesterol Não-HDL', category: 'LIPIDIOS' },
    'TRIGLYCERIDES': { key: 'TRIGLYCERIDES', name: 'Triglicerídeos', category: 'LIPIDIOS' },
    'TRIGLICERIDEOS': { key: 'TRIGLYCERIDES', name: 'Triglicerídeos', category: 'LIPIDIOS' },
    'TRIGLICERIDEO': { key: 'TRIGLYCERIDES', name: 'Triglicerídeos', category: 'LIPIDIOS' },
    'TRIGLICERIDES': { key: 'TRIGLYCERIDES', name: 'Triglicerídeos', category: 'LIPIDIOS' },
    'APOB': { key: 'APOB', name: 'Apolipoproteína B (Apo B)', category: 'LIPIDIOS' },
    'APOLIPOPROTEINA B': { key: 'APOB', name: 'Apolipoproteína B (Apo B)', category: 'LIPIDIOS' },
    'APO B': { key: 'APOB', name: 'Apolipoproteína B (Apo B)', category: 'LIPIDIOS' },
    'APOA1': { key: 'APOA1', name: 'Apolipoproteína A1 (Apo A1)', category: 'LIPIDIOS' },
    'APOLIPOPROTEINA A1': { key: 'APOA1', name: 'Apolipoproteína A1 (Apo A1)', category: 'LIPIDIOS' },
    'APO A1': { key: 'APOA1', name: 'Apolipoproteína A1 (Apo A1)', category: 'LIPIDIOS' },
    'LPA': { key: 'LPA', name: 'Lipoproteína (a) [Lp(a)]', category: 'LIPIDIOS' },
    'LIPOPROTEINA A': { key: 'LPA', name: 'Lipoproteína (a) [Lp(a)]', category: 'LIPIDIOS' },
    'LP(A)': { key: 'LPA', name: 'Lipoproteína (a) [Lp(a)]', category: 'LIPIDIOS' },
    'LIPIDES TOTAIS': { key: 'TOTAL_LIPIDS', name: 'Lípides Totais', category: 'LIPIDIOS' },
    'FOSFOLIPIDEOS': { key: 'PHOSPHOLIPIDS', name: 'Fosfolipídeos', category: 'LIPIDIOS' },
    'CASTELLI I': { key: 'CASTELLI_I', name: 'Índice de Castelli I', category: 'LIPIDIOS' },
    'INDICE DE CASTELLI I': { key: 'CASTELLI_I', name: 'Índice de Castelli I', category: 'LIPIDIOS' },
    'CASTELLI II': { key: 'CASTELLI_II', name: 'Índice de Castelli II', category: 'LIPIDIOS' },
    'INDICE DE CASTELLI II': { key: 'CASTELLI_II', name: 'Índice de Castelli II', category: 'LIPIDIOS' },

    // ── TIREOIDE ──
    'TSH': { key: 'TSH', name: 'TSH Ultra Sensível', category: 'TIREOIDE' },
    'TSH ULTRA SENSIVEL': { key: 'TSH', name: 'TSH Ultra Sensível', category: 'TIREOIDE' },
    'TSH ULTRA SENSÍVEL': { key: 'TSH', name: 'TSH Ultra Sensível', category: 'TIREOIDE' },
    'TSH ULTRASENSIVEL': { key: 'TSH', name: 'TSH Ultra Sensível', category: 'TIREOIDE' },
    'HORMONIO TIREOSTIMULANTE': { key: 'TSH', name: 'TSH Ultra Sensível', category: 'TIREOIDE' },
    'FREE_T4': { key: 'FREE_T4', name: 'T4 Livre', category: 'TIREOIDE' },
    'T4 LIVRE': { key: 'FREE_T4', name: 'T4 Livre', category: 'TIREOIDE' },
    'TIROXINA LIVRE': { key: 'FREE_T4', name: 'T4 Livre', category: 'TIREOIDE' },
    'TOTAL_T4': { key: 'TOTAL_T4', name: 'T4 Total', category: 'TIREOIDE' },
    'T4 TOTAL': { key: 'TOTAL_T4', name: 'T4 Total', category: 'TIREOIDE' },
    'FREE_T3': { key: 'FREE_T3', name: 'T3 Livre', category: 'TIREOIDE' },
    'T3 LIVRE': { key: 'FREE_T3', name: 'T3 Livre', category: 'TIREOIDE' },
    'TRIODOTIRONINA LIVRE': { key: 'FREE_T3', name: 'T3 Livre', category: 'TIREOIDE' },
    'TOTAL_T3': { key: 'TOTAL_T3', name: 'T3 Total', category: 'TIREOIDE' },
    'T3 TOTAL': { key: 'TOTAL_T3', name: 'T3 Total', category: 'TIREOIDE' },
    'REVERSE_T3': { key: 'REVERSE_T3', name: 'T3 Reverso', category: 'TIREOIDE' },
    'T3 REVERSO': { key: 'REVERSE_T3', name: 'T3 Reverso', category: 'TIREOIDE' },
    'ANTI_TPO': { key: 'ANTI_TPO', name: 'Anti-TPO (Anticorpo Anti-Tireoperoxidase)', category: 'TIREOIDE' },
    'ANTI TPO': { key: 'ANTI_TPO', name: 'Anti-TPO (Anticorpo Anti-Tireoperoxidase)', category: 'TIREOIDE' },
    'ANTI-TPO': { key: 'ANTI_TPO', name: 'Anti-TPO (Anticorpo Anti-Tireoperoxidase)', category: 'TIREOIDE' },
    'ANTICORPO ANTI TIREOPERONIDASE': { key: 'ANTI_TPO', name: 'Anti-TPO (Anticorpo Anti-Tireoperoxidase)', category: 'TIREOIDE' },
    'ANTI_TG': { key: 'ANTI_TG', name: 'Anti-TG (Anticorpo Anti-Tireoglobulina)', category: 'TIREOIDE' },
    'ANTI TG': { key: 'ANTI_TG', name: 'Anti-TG (Anticorpo Anti-Tireoglobulina)', category: 'TIREOIDE' },
    'TRAB': { key: 'TRAB', name: 'TRAB (Anticorpo Anti-Receptor de TSH)', category: 'TIREOIDE' },
    'THYROGLOBULIN': { key: 'THYROGLOBULIN', name: 'Tireoglobulina', category: 'TIREOIDE' },
    'TIREOGLOBULINA': { key: 'THYROGLOBULIN', name: 'Tireoglobulina', category: 'TIREOIDE' },

    // ── HEPATICO ──
    'AST': { key: 'AST', name: 'AST (TGO)', category: 'HEPATICO' },
    'TGO': { key: 'AST', name: 'AST (TGO)', category: 'HEPATICO' },
    'AST (TGO)': { key: 'AST', name: 'AST (TGO)', category: 'HEPATICO' },
    'ALT': { key: 'ALT', name: 'ALT (TGP)', category: 'HEPATICO' },
    'TGP': { key: 'ALT', name: 'ALT (TGP)', category: 'HEPATICO' },
    'ALT (TGP)': { key: 'ALT', name: 'ALT (TGP)', category: 'HEPATICO' },
    'GGT': { key: 'GGT', name: 'Gama-GT', category: 'HEPATICO' },
    'GAMA GT': { key: 'GGT', name: 'Gama-GT', category: 'HEPATICO' },
    'GAMA-GT': { key: 'GGT', name: 'Gama-GT', category: 'HEPATICO' },
    'ALP': { key: 'ALP', name: 'Fosfatase Alcalina', category: 'HEPATICO' },
    'FOSFATASE ALCALINA': { key: 'ALP', name: 'Fosfatase Alcalina', category: 'HEPATICO' },
    'FOSFATASE ALCALINA SERICA': { key: 'ALP', name: 'Fosfatase Alcalina', category: 'HEPATICO' },
    'TOTAL_BILIRUBIN': { key: 'TOTAL_BILIRUBIN', name: 'Bilirrubina Total', category: 'HEPATICO' },
    'BILIRRUBINA TOTAL': { key: 'TOTAL_BILIRUBIN', name: 'Bilirrubina Total', category: 'HEPATICO' },
    'DIRECT_BILIRUBIN': { key: 'DIRECT_BILIRUBIN', name: 'Bilirrubina Direta', category: 'HEPATICO' },
    'BILIRRUBINA DIRETA': { key: 'DIRECT_BILIRUBIN', name: 'Bilirrubina Direta', category: 'HEPATICO' },
    'INDIRECT_BILIRUBIN': { key: 'INDIRECT_BILIRUBIN', name: 'Bilirrubina Indireta', category: 'HEPATICO' },
    'BILIRRUBINA INDIRETA': { key: 'INDIRECT_BILIRUBIN', name: 'Bilirrubina Indireta', category: 'HEPATICO' },

    // ── RENAL ──
    'CREATININE': { key: 'CREATININE', name: 'Creatinina', category: 'RENAL' },
    'CREATININA': { key: 'CREATININE', name: 'Creatinina', category: 'RENAL' },
    'CREATININA SERICA': { key: 'CREATININE', name: 'Creatinina', category: 'RENAL' },
    'UREA': { key: 'UREA', name: 'Ureia', category: 'RENAL' },
    'UREIA': { key: 'UREA', name: 'Ureia', category: 'RENAL' },
    'UREIA SERICA': { key: 'UREA', name: 'Ureia', category: 'RENAL' },
    'BUN': { key: 'UREA', name: 'Ureia (BUN)', category: 'RENAL' },
    'EGFR': { key: 'EGFR', name: 'Taxa de Filtração Glomerular (eGFR)', category: 'RENAL' },
    'TAXA DE FILTRACAO': { key: 'EGFR', name: 'Taxa de Filtração Glomerular (eGFR)', category: 'RENAL' },
    'TFG': { key: 'EGFR', name: 'Taxa de Filtração Glomerular (eGFR)', category: 'RENAL' },
    'TFGE': { key: 'EGFR', name: 'Taxa de Filtração Glomerular (eGFR)', category: 'RENAL' },
    'URIC_ACID': { key: 'URIC_ACID', name: 'Ácido Úrico', category: 'RENAL' },
    'ACIDO URICO': { key: 'URIC_ACID', name: 'Ácido Úrico', category: 'RENAL' },
    'ACIDO URICO SERICO': { key: 'URIC_ACID', name: 'Ácido Úrico', category: 'RENAL' },
    'CYSTATIN_C': { key: 'CYSTATIN_C', name: 'Cistatina C', category: 'RENAL' },
    'CISTATINA C': { key: 'CYSTATIN_C', name: 'Cistatina C', category: 'RENAL' },
    'CLEARANCE_CREATININE': { key: 'CLEARANCE_CREATININE', name: 'Clearence de Creatinina', category: 'RENAL' },
    'CLEARENCE DE CREATININA': { key: 'CLEARANCE_CREATININE', name: 'Clearence de Creatinina', category: 'RENAL' },

    // ── VITAMINAS_MINERAIS ──
    'VITAMIN_D': { key: 'VITAMIN_D', name: 'Vitamina D (25-OH)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA D': { key: 'VITAMIN_D', name: 'Vitamina D (25-OH)', category: 'VITAMINAS_MINERAIS' },
    '25-HIDROXIVITAMINA D': { key: 'VITAMIN_D', name: 'Vitamina D (25-OH)', category: 'VITAMINAS_MINERAIS' },
    '25 HIDROXIVITAMINA D': { key: 'VITAMIN_D', name: 'Vitamina D (25-OH)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA D3': { key: 'VITAMIN_D', name: 'Vitamina D (25-OH)', category: 'VITAMINAS_MINERAIS' },
    'VITAMIN_B12': { key: 'VITAMIN_B12', name: 'Vitamina B12', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA B12': { key: 'VITAMIN_B12', name: 'Vitamina B12', category: 'VITAMINAS_MINERAIS' },
    'COBALAMINA': { key: 'VITAMIN_B12', name: 'Vitamina B12', category: 'VITAMINAS_MINERAIS' },
    'FOLIC_ACID': { key: 'FOLIC_ACID', name: 'Ácido Fólico (Vitamina B9)', category: 'VITAMINAS_MINERAIS' },
    'ACIDO FOLICO': { key: 'FOLIC_ACID', name: 'Ácido Fólico (Vitamina B9)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA B9': { key: 'FOLIC_ACID', name: 'Ácido Fólico (Vitamina B9)', category: 'VITAMINAS_MINERAIS' },
    'FOLATO': { key: 'FOLIC_ACID', name: 'Ácido Fólico (Vitamina B9)', category: 'VITAMINAS_MINERAIS' },
    'VITAMIN_B6': { key: 'VITAMIN_B6', name: 'Vitamina B6', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA B6': { key: 'VITAMIN_B6', name: 'Vitamina B6', category: 'VITAMINAS_MINERAIS' },
    'PIRIDOXAL 5 FOSFATO': { key: 'VITAMIN_B6', name: 'Vitamina B6', category: 'VITAMINAS_MINERAIS' },
    'VITAMIN_B1': { key: 'VITAMIN_B1', name: 'Vitamina B1 (Tiamina)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA B1': { key: 'VITAMIN_B1', name: 'Vitamina B1 (Tiamina)', category: 'VITAMINAS_MINERAIS' },
    'TIAMINA': { key: 'VITAMIN_B1', name: 'Vitamina B1 (Tiamina)', category: 'VITAMINAS_MINERAIS' },
    'VITAMIN_A': { key: 'VITAMIN_A', name: 'Vitamina A (Retinol)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA A': { key: 'VITAMIN_A', name: 'Vitamina A (Retinol)', category: 'VITAMINAS_MINERAIS' },
    'RETINOL': { key: 'VITAMIN_A', name: 'Vitamina A (Retinol)', category: 'VITAMINAS_MINERAIS' },
    'VITAMIN_E': { key: 'VITAMIN_E', name: 'Vitamina E (Alfa-Tocoferol)', category: 'VITAMINAS_MINERAIS' },
    'VITAMINA E': { key: 'VITAMIN_E', name: 'Vitamina E (Alfa-Tocoferol)', category: 'VITAMINAS_MINERAIS' },
    'FERRITIN': { key: 'FERRITIN', name: 'Ferritina', category: 'VITAMINAS_MINERAIS' },
    'FERRITINA': { key: 'FERRITIN', name: 'Ferritina', category: 'VITAMINAS_MINERAIS' },
    'FERRITINA SERICA': { key: 'FERRITIN', name: 'Ferritina', category: 'VITAMINAS_MINERAIS' },
    'FERRITINA SÉRICA': { key: 'FERRITIN', name: 'Ferritina', category: 'VITAMINAS_MINERAIS' },
    'IRON': { key: 'IRON', name: 'Ferro Sérico', category: 'VITAMINAS_MINERAIS' },
    'FERRO': { key: 'IRON', name: 'Ferro Sérico', category: 'VITAMINAS_MINERAIS' },
    'FERRO SERICO': { key: 'IRON', name: 'Ferro Sérico', category: 'VITAMINAS_MINERAIS' },
    'TRANSFERRIN': { key: 'TRANSFERRIN', name: 'Transferrina', category: 'VITAMINAS_MINERAIS' },
    'TRANSFERRINA': { key: 'TRANSFERRIN', name: 'Transferrina', category: 'VITAMINAS_MINERAIS' },
    'TIBC': { key: 'TIBC', name: 'Capacidade Total de Ligação do Ferro (TIBC)', category: 'VITAMINAS_MINERAIS' },
    'MAGNESIUM': { key: 'MAGNESIUM', name: 'Magnésio', category: 'VITAMINAS_MINERAIS' },
    'MAGNESIO': { key: 'MAGNESIUM', name: 'Magnésio', category: 'VITAMINAS_MINERAIS' },
    'MAGNESIO SERICO': { key: 'MAGNESIUM', name: 'Magnésio', category: 'VITAMINAS_MINERAIS' },
    'CALCIUM': { key: 'CALCIUM', name: 'Cálcio Total', category: 'VITAMINAS_MINERAIS' },
    'CALCIO': { key: 'CALCIUM', name: 'Cálcio Total', category: 'VITAMINAS_MINERAIS' },
    'CALCIO TOTAL': { key: 'CALCIUM', name: 'Cálcio Total', category: 'VITAMINAS_MINERAIS' },
    'IONIZED_CALCIUM': { key: 'IONIZED_CALCIUM', name: 'Cálcio Iônico', category: 'VITAMINAS_MINERAIS' },
    'CALCIO IONICO': { key: 'IONIZED_CALCIUM', name: 'Cálcio Iônico', category: 'VITAMINAS_MINERAIS' },
    'SODIUM': { key: 'SODIUM', name: 'Sódio', category: 'VITAMINAS_MINERAIS' },
    'SODIO': { key: 'SODIUM', name: 'Sódio', category: 'VITAMINAS_MINERAIS' },
    'SODIO SERICO': { key: 'SODIUM', name: 'Sódio', category: 'VITAMINAS_MINERAIS' },
    'POTASSIUM': { key: 'POTASSIUM', name: 'Potássio', category: 'VITAMINAS_MINERAIS' },
    'POTASSIO': { key: 'POTASSIUM', name: 'Potássio', category: 'VITAMINAS_MINERAIS' },
    'POTASSIO SERICO': { key: 'POTASSIUM', name: 'Potássio', category: 'VITAMINAS_MINERAIS' },
    'PHOSPHORUS': { key: 'PHOSPHORUS', name: 'Fósforo', category: 'VITAMINAS_MINERAIS' },
    'FOSFORO': { key: 'PHOSPHORUS', name: 'Fósforo', category: 'VITAMINAS_MINERAIS' },
    'ZINC': { key: 'ZINC', name: 'Zinco', category: 'VITAMINAS_MINERAIS' },
    'ZINCO': { key: 'ZINC', name: 'Zinco', category: 'VITAMINAS_MINERAIS' },
    'ZINCO (SORO)': { key: 'ZINC', name: 'Zinco', category: 'VITAMINAS_MINERAIS' },
    'COPPER': { key: 'COPPER', name: 'Cobre Sérico', category: 'VITAMINAS_MINERAIS' },
    'COBRE': { key: 'COPPER', name: 'Cobre Sérico', category: 'VITAMINAS_MINERAIS' },
    'SELENIUM': { key: 'SELENIUM', name: 'Selênio', category: 'VITAMINAS_MINERAIS' },
    'SELENIO': { key: 'SELENIUM', name: 'Selênio', category: 'VITAMINAS_MINERAIS' },

    // ── HORMONIOS ──
    'TOTAL_TESTOSTERONE': { key: 'TOTAL_TESTOSTERONE', name: 'Testosterona Total', category: 'HORMONIOS' },
    'TESTOSTERONA TOTAL': { key: 'TOTAL_TESTOSTERONE', name: 'Testosterona Total', category: 'HORMONIOS' },
    'TESTOSTERONA': { key: 'TOTAL_TESTOSTERONE', name: 'Testosterona Total', category: 'HORMONIOS' },
    'FREE_TESTOSTERONE': { key: 'FREE_TESTOSTERONE', name: 'Testosterona Livre Calculada', category: 'HORMONIOS' },
    'TESTOSTERONA LIVRE': { key: 'FREE_TESTOSTERONE', name: 'Testosterona Livre Calculada', category: 'HORMONIOS' },
    'TESTOSTERONA LIVRE CALCULADA': { key: 'FREE_TESTOSTERONE', name: 'Testosterona Livre Calculada', category: 'HORMONIOS' },
    'DHT': { key: 'DHT', name: 'Dihidrotestosterona (DHT)', category: 'HORMONIOS' },
    'DIHIDROTESTOSTERONA': { key: 'DHT', name: 'Dihidrotestosterona (DHT)', category: 'HORMONIOS' },
    'SHBG': { key: 'SHBG', name: 'SHBG (Globulina Ligadora)', category: 'HORMONIOS' },
    'GLOBULINA LIGADORA DE HORMONIOS SEXUAIS': { key: 'SHBG', name: 'SHBG (Globulina Ligadora)', category: 'HORMONIOS' },
    'ESTRADIOL': { key: 'ESTRADIOL', name: 'Estradiol (E2)', category: 'HORMONIOS' },
    'ESTRONA': { key: 'ESTRONE', name: 'Estrona (E1)', category: 'HORMONIOS' },
    'PROGESTERONE': { key: 'PROGESTERONE', name: 'Progesterona', category: 'HORMONIOS' },
    'PROGESTERONA': { key: 'PROGESTERONE', name: 'Progesterona', category: 'HORMONIOS' },
    'PROLACTIN': { key: 'PROLACTIN', name: 'Prolactina', category: 'HORMONIOS' },
    'PROLACTINA': { key: 'PROLACTIN', name: 'Prolactina', category: 'HORMONIOS' },
    'LH': { key: 'LH', name: 'LH (Hormônio Luteinizante)', category: 'HORMONIOS' },
    'HORMONIO LUTEINIZANTE': { key: 'LH', name: 'LH (Hormônio Luteinizante)', category: 'HORMONIOS' },
    'FSH': { key: 'FSH', name: 'FSH (Hormônio Folículo Estimulante)', category: 'HORMONIOS' },
    'HORMONIO FOLICULO ESTIMULANTE': { key: 'FSH', name: 'FSH (Hormônio Folículo Estimulante)', category: 'HORMONIOS' },
    'DHEA': { key: 'DHEA', name: 'DHEA', category: 'HORMONIOS' },
    'DESIDROEPIANDROSTERONA': { key: 'DHEA', name: 'DHEA', category: 'HORMONIOS' },
    'DHEA_S': { key: 'DHEA_S', name: 'DHEA-S (Sulfato de DHEA)', category: 'HORMONIOS' },
    'SULFATO DE DHEA': { key: 'DHEA_S', name: 'DHEA-S (Sulfato de DHEA)', category: 'HORMONIOS' },
    'SDHEA': { key: 'DHEA_S', name: 'DHEA-S (Sulfato de DHEA)', category: 'HORMONIOS' },
    'CORTISOL': { key: 'CORTISOL', name: 'Cortisol Basal', category: 'HORMONIOS' },
    'CORTISOL BASAL': { key: 'CORTISOL', name: 'Cortisol Basal', category: 'HORMONIOS' },
    'ACTH': { key: 'ACTH', name: 'ACTH (Hormônio Adrenocorticotrófico)', category: 'HORMONIOS' },
    'GH': { key: 'GH', name: 'GH (Hormônio do Crescimento)', category: 'HORMONIOS' },
    'IGF1': { key: 'IGF1', name: 'IGF-1 (Somatomedina C)', category: 'HORMONIOS' },
    'IGF-1': { key: 'IGF1', name: 'IGF-1 (Somatomedina C)', category: 'HORMONIOS' },
    'SOMATOMEDINA C': { key: 'IGF1', name: 'IGF-1 (Somatomedina C)', category: 'HORMONIOS' },
    'PTH': { key: 'PTH', name: 'PTH Intacto (Paratormônio)', category: 'HORMONIOS' },
    'PARATORMONIO': { key: 'PTH', name: 'PTH Intacto (Paratormônio)', category: 'HORMONIOS' },
    'ALDOSTERONE': { key: 'ALDOSTERONE', name: 'Aldosterona', category: 'HORMONIOS' },
    'ALDOSTERONA': { key: 'ALDOSTERONE', name: 'Aldosterona', category: 'HORMONIOS' },

    // ── INFLAMACAO ──
    'HS_CRP': { key: 'HS_CRP', name: 'Proteína C-Reativa (PCR-us)', category: 'INFLAMACAO' },
    'PCR': { key: 'HS_CRP', name: 'Proteína C-Reativa (PCR-us)', category: 'INFLAMACAO' },
    'PROTEINA C REATIVA': { key: 'HS_CRP', name: 'Proteína C-Reativa (PCR-us)', category: 'INFLAMACAO' },
    'PCR ULTRA SENSIVEL': { key: 'HS_CRP', name: 'Proteína C-Reativa (PCR-us)', category: 'INFLAMACAO' },
    'PCR-US': { key: 'HS_CRP', name: 'Proteína C-Reativa (PCR-us)', category: 'INFLAMACAO' },
    'HOMOCYSTEINE': { key: 'HOMOCYSTEINE', name: 'Homocisteína', category: 'INFLAMACAO' },
    'HOMOCISTEINA': { key: 'HOMOCYSTEINE', name: 'Homocisteína', category: 'INFLAMACAO' },
    'ESR': { key: 'ESR', name: 'VHS (Velocidade de Hemossedimentação)', category: 'INFLAMACAO' },
    'VHS': { key: 'ESR', name: 'VHS (Velocidade de Hemossedimentação)', category: 'INFLAMACAO' },
    'FIBRINOGEN': { key: 'FIBRINOGEN', name: 'Fibrinogênio', category: 'INFLAMACAO' },
    'FIBRINOGENIO': { key: 'FIBRINOGEN', name: 'Fibrinogênio', category: 'INFLAMACAO' },
    'CPK': { key: 'CPK', name: 'CPK (Creatinofosfoquinase)', category: 'INFLAMACAO' },
    'CK': { key: 'CPK', name: 'CPK (Creatinofosfoquinase)', category: 'INFLAMACAO' },
    'CK_MB': { key: 'CK_MB', name: 'CK-MB', category: 'INFLAMACAO' },
    'CK-MB': { key: 'CK_MB', name: 'CK-MB', category: 'INFLAMACAO' },
    'TROPONIN': { key: 'TROPONIN', name: 'Troponina I', category: 'INFLAMACAO' },
    'TROPONINA': { key: 'TROPONIN', name: 'Troponina I', category: 'INFLAMACAO' },
    'NT_PROBNP': { key: 'NT_PROBNP', name: 'NT-proBNP', category: 'INFLAMACAO' },
    'NT-PROBNP': { key: 'NT_PROBNP', name: 'NT-proBNP', category: 'INFLAMACAO' },

    // ── MARCADORES_TUMORAIS ──
    'PSA_TOTAL': { key: 'PSA_TOTAL', name: 'PSA Total', category: 'MARCADORES_TUMORAIS' },
    'PSA TOTAL': { key: 'PSA_TOTAL', name: 'PSA Total', category: 'MARCADORES_TUMORAIS' },
    'PSA': { key: 'PSA_TOTAL', name: 'PSA Total', category: 'MARCADORES_TUMORAIS' },
    'PSA_FREE': { key: 'PSA_FREE', name: 'PSA Livre', category: 'MARCADORES_TUMORAIS' },
    'PSA LIVRE': { key: 'PSA_FREE', name: 'PSA Livre', category: 'MARCADORES_TUMORAIS' },
    'CEA': { key: 'CEA', name: 'CEA (Antígeno Carcinoembrionário)', category: 'MARCADORES_TUMORAIS' },
    'CA_125': { key: 'CA_125', name: 'CA 125', category: 'MARCADORES_TUMORAIS' },
    'CA 125': { key: 'CA_125', name: 'CA 125', category: 'MARCADORES_TUMORAIS' },
    'CA125': { key: 'CA_125', name: 'CA 125', category: 'MARCADORES_TUMORAIS' },
    'CA_19_9': { key: 'CA_19_9', name: 'CA 19-9', category: 'MARCADORES_TUMORAIS' },
    'CA 19-9': { key: 'CA_19_9', name: 'CA 19-9', category: 'MARCADORES_TUMORAIS' },
    'AFP': { key: 'AFP', name: 'Alfa-Fetoproteína (AFP)', category: 'MARCADORES_TUMORAIS' },

    // ── HEMOGRAMA ──
    'HEMACIAS': { key: 'RBC', name: 'Hemácias (Eritrócitos)', category: 'HEMOGRAMA' },
    'ERITROCITOS': { key: 'RBC', name: 'Hemácias (Eritrócitos)', category: 'HEMOGRAMA' },
    'RBC': { key: 'RBC', name: 'Hemácias (Eritrócitos)', category: 'HEMOGRAMA' },
    'HEMOGLOBIN': { key: 'HEMOGLOBIN', name: 'Hemoglobina', category: 'HEMOGRAMA' },
    'HEMOGLOBINA': { key: 'HEMOGLOBIN', name: 'Hemoglobina', category: 'HEMOGRAMA' },
    'HEMATOCRIT': { key: 'HEMATOCRIT', name: 'Hematócrito', category: 'HEMOGRAMA' },
    'HEMATOCRITO': { key: 'HEMATOCRIT', name: 'Hematócrito', category: 'HEMOGRAMA' },
    'MCV': { key: 'MCV', name: 'VCM (Volume Corpuscular Médio)', category: 'HEMOGRAMA' },
    'VCM': { key: 'MCV', name: 'VCM (Volume Corpuscular Médio)', category: 'HEMOGRAMA' },
    'VOLUME CORPUSCULAR MEDIO': { key: 'MCV', name: 'VCM (Volume Corpuscular Médio)', category: 'HEMOGRAMA' },
    'MCH': { key: 'MCH', name: 'HCM (Hemoglobina Corpuscular Média)', category: 'HEMOGRAMA' },
    'HCM': { key: 'MCH', name: 'HCM (Hemoglobina Corpuscular Média)', category: 'HEMOGRAMA' },
    'MCHC': { key: 'MCHC', name: 'CHCM (Conc. Hemoglobina Corpuscular Média)', category: 'HEMOGRAMA' },
    'CHCM': { key: 'MCHC', name: 'CHCM (Conc. Hemoglobina Corpuscular Média)', category: 'HEMOGRAMA' },
    'RDW': { key: 'RDW', name: 'RDW (Variabilidade de Hemácias)', category: 'HEMOGRAMA' },
    'R.D.W.': { key: 'RDW', name: 'RDW (Variabilidade de Hemácias)', category: 'HEMOGRAMA' },
    'WBC': { key: 'WBC', name: 'Leucócitos', category: 'HEMOGRAMA' },
    'LEUCOCITOS': { key: 'WBC', name: 'Leucócitos', category: 'HEMOGRAMA' },
    'LEUCOCITOS TOTAIS': { key: 'WBC', name: 'Leucócitos', category: 'HEMOGRAMA' },
    'NEUTROFILOS': { key: 'NEUTROPHILS', name: 'Neutrófilos Totais', category: 'HEMOGRAMA' },
    'BASTONETES': { key: 'BAND_NEUTROPHILS', name: 'Bastonetes', category: 'HEMOGRAMA' },
    'SEGMENTADOS': { key: 'SEGMENTED_NEUTROPHILS', name: 'Segmentados', category: 'HEMOGRAMA' },
    'EOSINOFILOS': { key: 'EOSINOPHILS', name: 'Eosinófilos', category: 'HEMOGRAMA' },
    'BASOFILOS': { key: 'BASOPHILS', name: 'Basófilos', category: 'HEMOGRAMA' },
    'MONOCITOS': { key: 'MONOCYTES', name: 'Monócitos', category: 'HEMOGRAMA' },
    'LINFOCITOS': { key: 'LYMPHOCYTES', name: 'Linfócitos', category: 'HEMOGRAMA' },
    'LINFOCITOS %': { key: 'LYMPHOCYTE_PCT', name: 'Linfócitos (%)', category: 'HEMOGRAMA' },
    'LINFOCITOS PERCENTUAL': { key: 'LYMPHOCYTE_PCT', name: 'Linfócitos (%)', category: 'HEMOGRAMA' },
    'LYMPHOCYTE_PCT': { key: 'LYMPHOCYTE_PCT', name: 'Linfócitos (%)', category: 'HEMOGRAMA' },
    'LINFOCITOS REATIVOS': { key: 'REACTIVE_LYMPHOCYTES', name: 'Linfócitos Reativos', category: 'HEMOGRAMA' },
    'PLATELETS': { key: 'PLATELETS', name: 'Plaquetas', category: 'HEMOGRAMA' },
    'PLAQUETAS': { key: 'PLATELETS', name: 'Plaquetas', category: 'HEMOGRAMA' },
    'VPM': { key: 'MPV', name: 'Volume Plaquetário Médio (VPM)', category: 'HEMOGRAMA' },
  };

  normalize(name: string): { key: string; name: string; category: string } {
    const cleanRaw = name.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();
    // Compact representation without any non-alphanumeric chars (e.g., "V.C.M." -> "VCM", "AST (TGO)" -> "ASTTGO")
    const cleanCompact = cleanRaw.replace(/[^A-Z0-9]/g, '');
    // Word representation with spaces (e.g., "AST (TGO)" -> "AST TGO")
    const cleanWords = cleanRaw.replace(/[^A-Z0-9]/g, ' ').replace(/\s+/g, ' ').trim();

    // ── Pass 1: Exact Match on Compact String (Highest Priority) ──
    for (const [pattern, entry] of Object.entries(this.dictionary)) {
      const patternCompact = pattern.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^A-Z0-9]/g, '');
      if (cleanCompact === patternCompact) {
        return entry;
      }
    }

    // ── Pass 2: Whole Word Boundary Match (Prevents "Bastonetes" matching "AST") ──
    for (const [pattern, entry] of Object.entries(this.dictionary)) {
      const patternWords = pattern.toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^A-Z0-9]/g, ' ').replace(/\s+/g, ' ').trim();
      if (patternWords.length >= 2) {
        const regex = new RegExp(`\\b${patternWords}\\b`, 'i');
        if (regex.test(cleanWords)) {
          return entry;
        }
      }
    }

    // ── Fallback ──
    return {
      key: cleanCompact.substring(0, 30) || 'BIOMARKER',
      name: name,
      category: 'OUTROS',
    };
  }
}
